name: "BLE integration"
version: "0.0.22"
slug: "ble_integration"
description: "An add-on to integrate BLE devices with Home Assistant via MQTT."
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
init: false
host_dbus: true

homeassistant_api: true

# 對外開放 8099
ingress: false
ports:
  "8080/tcp": 8080
ports_description:
  "8080/tcp": "BLE HTTP API and Status page"
# 在 Add-on 頁面顯示「Open Web UI」按鈕（連到 /status）
webui: "http://[HOST]:[PORT:8080]/status"
panel_icon: "mdi:view-list-outline"


map:
  - share:rw

options:
  mqtt_username: "test"
  mqtt_password: "test"

schema:
  mqtt_username: str?
  mqtt_password: str?
  # ota_ip: str

  
