name: "BLE integration"
version: "0.0.2"
slug: "ble_integration"
description: 
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
init: false
host_dbus: true

homeassistant_api: true

map:
  - share:rw

options:

  mqtt_username: "test"
  mqtt_password: "test"

schema:
  mqtt_username: str?
  mqtt_password: str?
  # ota_ip: str

  
