name: "BLE integration"
version: "0.1.0"
slug: "ble_integration"
description: "This Home Assistant add-on listens to MQTT messages and automatically handles
  ZP2 firmware checks, OTA updates, and MQTT Discovery for ZP2 devices.
  It enables seamless integration of ZP2 device data into Home Assistant."
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true

# BLE / BlueZ 通常需要 DBus
host_dbus: true

# Web UI
webui: "http://[HOST]:8080"
ports:
  8080/tcp: 8080

map:
  - share:rw

# privileged: true

options: {}
schema: {}


  
